src/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password-change/', views.PasswordChangeView.as_view(),
         name='password-change'),
    path('password-reset/', views.PasswordResetView.as_view(),
         name='password-reset'),
    path('password-reset-done/', views.PasswordResetDoneView.as_view(),
         name='password-reset-done'),
    path('password-reset/<uuid:uidb64>/<slug:token>/',
         views.PasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
]

src/deck/urls.py
from django.conf.urls import url
from django.urls import path, include


# /deck/

app_name = 'deck'


from . import views

urlpatterns = [
    
    # url(r'(?P<random_url>[-\w]+)/$', views.index, name='index'),
    url('', views.index, name='index'),


]

src/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('me/', views.ShowProfile.as_view(), name='show_self'),
    path('me/edit/', views.EditProfile.as_view(), name='edit_self'),
    path('<slug:slug>/', views.ShowProfile.as_view(),
         name='show'),
]

src/deck/models.py
from django.db import models

# Create your models here.

src/deck/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


from django.shortcuts import redirect

def index(request):
    # return HttpResponse("Under construction.")
    return render(request, "deck.html")

src/templates/_brandname.html
Flashy

src/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">About</a></li>

src/templates/about.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }}About{% endblock %}
{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}
<!-- Benefits of the Django application -->
{% block container %}
<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">An Awesome Tagline Goes Here</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">The Wonderful People Behind the Site</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/9/" alt="profile pic"></div>
        <p class="heavy text-center">Cassidy Coder</p>
        <h2>Front-end developer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/2/" alt="profile pic"></div>
        <p class="heavy text-center">James King</p>
        <h2>CEO</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/1/" alt="profile pic"></div>
        <p class="heavy text-center">Kate Lamport</p>
        <h2>Front-end designer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Edge Solutions Ltd.</strong><br>
            Taj Mahal<br>
            Agra<br>
            Uttar Pradesh<br>
            India - 282001<br>
            <abbr>P:</abbr> +91 0562 222 6431
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(27.176141, 78.042370);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    <!-- {% load thumbnail %} -->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Kevin Sweeney">
    <link rel="shortcut icon" href="{% static '/ico/flashcard.ico' %}">
    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>
    <link href="{% static '/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static '/css/cover.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock css %}
  </head>

{% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" style='z-index: 0;' role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static '/img/flash.png' %}" alt="logo">
              <!-- {% include "_brandname.html" %} -->
            {% endblock navbar-brand %}
          </a>

        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <!-- {% block navbar-left %}{% endblock %}      this is HOME/ABOUT section -->
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			             <img src="{% thumbnail user.profile.picture|default:'profile.png' 30x30 %}" alt="" />
			             {{ user.get_full_name|truncatechars:20 }}
			             <span class="caret"></span>
		                  </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock navbar-right %}
          </ul>
          <!-- </ul> -->
        </div><!--/.nav-collapse -->
        {% endblock navbar-menu %}
    </div>
    
{% endblock navbar %}




{% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}   
{% endblock messages %}




<div class="site-wrapper">
  <div class="site-wrapper-inner">



{% block container %}
    <div class="container">
      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>
    </div><!-- /.container -->
{% endblock container %}

  </div>
</div>

    
    {% block footer %}
      <!-- Some social button for contact will do 
      <a name="contact"></a>
      <div class="container">
        <div class="footer">
         <div class="row">
          <div class="col-lg-6">
              <p>&copy; Company {% now 'Y' %}</p>
          </div>
         </div>
        </div>
      </div> -->
    {% endblock footer %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/site.js' %}"></script>
    {% block scripts %}
    <!-- add unique scripts here -->
    {% endblock scripts %}
  </body>
</html>



src/templates/deck.html
{% extends "base.html" %}
{% load staticfiles %}


{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Deck{% endblock %}


{% block css %}
    <!-- <link href="{% static '/css/flip.css' %}" rel="stylesheet"> -->
{% endblock css %}

{% block navbar %}

    <div class="navbar navbar-default navbar-fixed-top navbar-transparent" role="navigation">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static '/img/flash.png' %}" alt="logo">
              <!-- {% include "_brandname.html" %} -->
            {% endblock %}
          </a>
        </div>
    </div>

{% endblock navbar %}



{% block container %}


        <form class="form-inline">
            <div class="form-group">  
                <input class="form-control input-lg" id="team_name" type="text" name="deck_name" placeholder="Name Deck">
                <input class="input-lg" id="exampleInputFile" type="file">
            </div>
        </form>
        <div style="padding:1em;">  </div>
        <form class="form-horizontal">
            <div class="form-group"> 
                <textarea class="form-control input-lg" type="text" rows="12" placeholder="Type or copy and paste flashcard text here."></textarea>
            </div>
            <div>  
                <button type="submit" class="btn-lg btn-primary" href="{% url 'deck:index' %}">Submit</button> 
                </label>
            </div>
        </form>




<!-- <form class="form-inline">
  <div class="form-group">
    <label for="exampleInputName2">Name</label>
    <input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail2">Email</label>
    <input type="email" class="form-control" id="exampleInputEmail2" placeholder="jane.doe@example.com">
  </div>
  <button type="submit" class="btn btn-default">Send invitation</button>
</form> -->

{% endblock container %}


src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock navbar-left %}

{% block navbar-right %}
          {% if not user.is_authenticated %}
                <a class="btn btn-danger btn-lg" href="{% url 'accounts:login' %}" role="button">Log in</a>
                <a class="btn btn-primary btn-lg" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
          {% else %}
            {{ block.super }}
          {% endif %}
{% endblock navbar-right %}



{% block container %}

                <!-- <h1>{% include "_brandname.html" %}</h1> -->
              <h1 class="myfont" style="font-size:5em;">Flashcards</h1>


              <h2 style="line-height: 1.6">
                <p class="myfont">Study Whenever.<br>
                Copy and paste material to automatically create study cards.<br>
                Just save the URL.<br> Bookmark. Email. Or share. <br>
                </p>
              </h2>
              <div style="padding:2em;"></div>
               <a class="btn-lg btn-success btn-primary" href="{% url 'deck:index' %}" role="button">Create Deck</a>

{% endblock container %}


